image:
  repository: "registry.fits.cloud/cloud-native/images/qualys/agent"
  pullPolicy: Always
  tag: "latest"

agent:
  activationId: ""
  customerId: ""
  serverUri: ""
  proxy: ""

# Makes pods runnable on all nodes including master node.
tolerations:
- operator: Exists
  effect: NoSchedule
- operator: Exists
  effect: PreferNoSchedule
- operator: Exists
  effect: NoExecute
