//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
2026 Copyright metal-stack Authors.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	qca "github.com/fi-ts/gardener-extension-qca/pkg/apis/qca"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*QCAConfig)(nil), (*qca.QCAConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_QCAConfig_To_qca_QCAConfig(a.(*QCAConfig), b.(*qca.QCAConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*qca.QCAConfig)(nil), (*QCAConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_qca_QCAConfig_To_v1alpha1_QCAConfig(a.(*qca.QCAConfig), b.(*QCAConfig), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_QCAConfig_To_qca_QCAConfig(in *QCAConfig, out *qca.QCAConfig, s conversion.Scope) error {
	out.TenantId = in.TenantId
	return nil
}

// Convert_v1alpha1_QCAConfig_To_qca_QCAConfig is an autogenerated conversion function.
func Convert_v1alpha1_QCAConfig_To_qca_QCAConfig(in *QCAConfig, out *qca.QCAConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_QCAConfig_To_qca_QCAConfig(in, out, s)
}

func autoConvert_qca_QCAConfig_To_v1alpha1_QCAConfig(in *qca.QCAConfig, out *QCAConfig, s conversion.Scope) error {
	out.TenantId = in.TenantId
	return nil
}

// Convert_qca_QCAConfig_To_v1alpha1_QCAConfig is an autogenerated conversion function.
func Convert_qca_QCAConfig_To_v1alpha1_QCAConfig(in *qca.QCAConfig, out *QCAConfig, s conversion.Scope) error {
	return autoConvert_qca_QCAConfig_To_v1alpha1_QCAConfig(in, out, s)
}
